[device]
name = "my_device"
address = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
autoconnect = true

[services.battery]
uuid = "180f"

[services.battery.characteristics.level]
uuid = "2a19"

[commands.read_battery]
command_type = "read"
service = "battery"
characteristic = "level"

[commands.sub_battery]
command_type = "notify"
service = "battery"
characteristic = "level"
