[device]
name = "my_device"
address = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
autoconnect = false

[services.hrs]
uuid = "180d"

[services.hrs.characteristics.mesurement]
uuid = "2a37"

[services.hrs.characteristics.location]
uuid = "2a38"

[commands.get_location]
command_type = "read"
service = "hrs"
characteristic = "location"

[commands.get_rate]
command_type = "read"
service = "hrs"
characteristic = "mesurement"
